USE `jersey`;

INSERT INTO `CUSTOMER`(`FIRST_NAME`, `LAST_NAME`) VALUES ('Stephen', 'Curry');
INSERT INTO `CUSTOMER`(`FIRST_NAME`, `LAST_NAME`) VALUES ('Lebron', 'James');
INSERT INTO `CUSTOMER`(`FIRST_NAME`, `LAST_NAME`) VALUES ('Michael', 'Jordan');
INSERT INTO `CUSTOMER`(`FIRST_NAME`, `LAST_NAME`) VALUES ('Kobe', 'Bryant');
INSERT INTO `CUSTOMER`(`FIRST_NAME`, `LAST_NAME`) VALUES ('Klay', 'Thompson');
INSERT INTO `CUSTOMER`(`FIRST_NAME`, `LAST_NAME`) VALUES ('Draymond', 'Green');
INSERT INTO `CUSTOMER`(`FIRST_NAME`, `LAST_NAME`) VALUES ('Kevin', 'Durant');
