
USE `jersey`;

DROP TABLE IF EXISTS `CUSTOMER`;

CREATE TABLE IF NOT EXISTS `CUSTOMER` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(64) NOT NULL,
  `LAST_NAME` VARCHAR(64) NOT NULL
) ENGINE=InnoDB;
